name: Deploy Express App
on:
  push:
    branches: [main] # or master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VPS and Update
        uses: appleboy/ssh-action@master
        with:
          host: 72.61.224.90
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/api.medcasts.com/public_html
            git pull origin main
            npm install --production
            pm2 restart medcasts-api || pm2 start index.js --name medcasts-api
